<?php

namespace App\Enums;

use App\Models\Log;

enum LogInstance: string
{
    case ENGINE = 'engine';
    case DEVICE = 'device';
    case UNKNOWN = 'unknown';

    public static function toArray(): array
    {
        return [
            self::ENGINE,
            self::DEVICE,
            self::UNKNOWN,
        ];
    }

    public static function labels(): array
    {
        return [
            self::ENGINE->label(),
            self::DEVICE->label(),
            self::UNKNOWN->label(),
        ];
    }

    public static function values(): array
    {
        return [
            self::ENGINE->value,
            self::DEVICE->value,
            self::UNKNOWN->value,
        ];
    }

    public static function labelAndValues(): array
    {
        return [
            ['label' => self::ENGINE->label(), 'value' => self::ENGINE->value],
            ['label' => self::DEVICE->label(), 'value' => self::DEVICE->value],
            ['label' => self::UNKNOWN->label(), 'value' => self::UNKNOWN->value],
        ];
    }

    public function label(): string
    {
        return match ($this) {
            self::ENGINE => 'Engine',
            self::DEVICE => 'Device',
            default => 'Unknown',
        };
    }

    public function description(): string
    {
        return match ($this) {
            self::ENGINE => 'Engine logs are generated by the application engine.',
            self::DEVICE => 'Device logs are generated by the network devices.',
            default => 'Unknown',
        };
    }

    public function badge(Log $log): string
    {
        return match ($this) {
            self::ENGINE => '<span class="whitespace-nowrap rounded-full px-2.5 py-0.5 text-xs bg-gray-100 text-gray-600">engine</span>',
            self::DEVICE => '<span class="whitespace-nowrap rounded-full px-2.5 py-0.5 text-xs bg-orange-100 text-orange-600">'.$log->instance.'</span>',
            default => '<span class="whitespace-nowrap rounded-full bg-gray-100 px-2.5 py-0.5 text-xs text-gray-600">unknown</span>',
        };
    }
}
